### Create patient

POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "one aaaatr",
  "dateOfBirth": "2000-01-20",
  "email": "test23@gmail.com",
  "address": "4 Somewhere street, Paris",
  "registeredDate": "2024-01-01"
}