### login request to retreive token
POST http://localhost:4004/auth/login
Content-Type: application/json

{
    "email": "newuser@test.com",
    "password": "Test1234"
}
> {% client.global.set("token", response.body.token) %}